export enum ConfigSetting {
  ProjectRootPath = 'projectRootPath',
  KarmaConfFilePath = 'karmaConfFilePath',
  KarmaProcessExecutable = 'karmaProcessExecutable',
  KarmaPort = 'karmaPort',
  Browser = 'browser',
  CustomLauncher = 'customLauncher',
  TestsBasePath = 'testsBasePath',
  TestFiles = 'testFiles',
  ExcludeFiles = 'excludeFiles',
  TestGrouping = 'testGrouping',
  FlattenSingleChildFolders = 'flattenSingleChildFolders',
  ReloadOnChangedFiles = 'reloadOnChangedFiles',
  ReloadOnKarmaConfigChange = 'reloadOnKarmaConfigChange',
  DefaultSocketConnectionPort = 'defaultSocketConnectionPort',
  DebuggerConfig = 'debuggerConfig',
  DebuggerConfigName = 'debuggerConfigName',
  LogLevel = 'logLevel',
  KarmaLogLevel = 'karmaLogLevel',
  Env = 'env',
  EnvFile = 'envFile',
  AutoWatchEnabled = 'autoWatchEnabled',
  AutoWatchBatchDelay = 'autoWatchBatchDelay',
  KarmaReadyTimeout = 'karmaReadyTimeout',
  TestFramework = 'testFramework',
  DefaultAngularProjectName = 'defaultAngularProjectName',
  ContainerModeEnabled = 'containerModeEnabled'
}
