export enum ConfigSetting {
	ProjectRootPath = 'projectRootPath',
	KarmaConfFilePath = 'karmaConfFilePath',
	KarmaProcessExecutable = 'karmaProcessExecutable',
	KarmaPort = 'karmaPort',
	Browser = 'browser',
	CustomLauncher = 'customLauncher',
	TestsBasePath = 'testsBasePath',
	TestFiles = 'testFiles',
	ExcludeFiles = 'excludeFiles',
	TestGrouping = 'testGrouping',
	FlattenSingleChildFolders = 'flattenSingleChildFolders',
	ReloadWatchedFiles = 'reloadWatchedFiles',
	ReloadOnKarmaConfigurationFileChange = 'reloadOnKarmaConfigurationFileChange',
	DefaultSocketConnectionPort = 'defaultSocketConnectionPort',
	DebuggerConfig = 'debuggerConfig',
	DebugLoggingEnabled = 'debugLoggingEnabled',
	Env = 'env',
	EnvFile = 'envFile',
	LogPanel = 'logpanel',
	LogFile = 'logfile',
	AutoWatchEnabled = 'autoWatchEnabled',
	AutoWatchBatchDelay = 'autoWatchBatchDelay',
	KarmaReadyTimeout = 'karmaReadyTimeout',
	TestFramework = 'testFramework'
}
