export enum ConfigSetting {
  ProjectRootPath = "projectRootPath",
  KarmaConfFilePath = "karmaConfFilePath",
  KarmaProcessExecutable = "karmaProcessExecutable",
  KarmaPort = "karmaPort",
  TestFiles = "testFiles",
  ExcludeFiles = "excludeFiles",
  TestGrouping = "testGrouping",
  FlattenSingleChildFolders = "flattenSingleChildFolders",
  ReloadWatchedFiles = "reloadWatchedFiles",
  ReloadOnKarmaConfigurationFileChange = "reloadOnKarmaConfigurationFileChange",
  DefaultSocketConnectionPort = "defaultSocketConnectionPort",
  DebuggerConfig = "debuggerConfig",
  DebugLevelLoggingEnabled = "debugLevelLoggingEnabled",
  Env = "env",
  EnvFile = "envFile",
  LogPanel = "logpanel",
  LogFile = "logfile",
  AutoWatchEnabled = "autoWatchEnabled"
}
